const express = require("express")
const router = express.Router()
const adminController=require('../controllers/adminController')

router.get("/home", adminController.home)
router.get('/user-management',adminController.user_management)
router.post('/add-user',adminController.add_user)
router.get('/file-management',adminController.file_management)
router.post('/files/add',adminController.add_file)
router.get('/files/delete/:name',adminController.delete_file)
router.post('/files/profile/upload-image/:uuid',adminController.upload_profile_image)
router.get('/news-management',adminController.news_management)
router.get('/news-item/:id',adminController.news_item)
router.get('/delete-news/:id',adminController.delete_news)
router.post('/news-upload',adminController.upload_news)
router.get('/data-management',adminController.data_management)
router.post('/add-parent',adminController.add_parent)
router.post('/add-teacher',adminController.add_teacher)
router.post('/add-student',adminController.add_student)
router.post('/bulk-update',adminController.bulk_update)
router.get('/academics',adminController.academics_management)
router.post('/academics',adminController.academics_management)
router.post('/exam-type',adminController.add_exam_type)
router.get('/finances',adminController.finance_management)
router.post('/finances',adminController.finance_management)
router.get('/profile',adminController.admin_profile)
router.get('/edit-profile/:uuid',adminController.edit_profile)
router.post('/edit-profile/:uuid',adminController.edit_profile)
router.get('/change-password/:uuid',adminController.change_password)
router.post('/change-password/:uuid',adminController.change_password)
router.get('/progress-charts',adminController.progress_charts)
router.get('/reports',adminController.reports)
router.post('/send-results',adminController.sendResults)

module.exports = router;
